apiVersion: v1
kind: Pod
metadata:
  name: nginx-nodepod
  labels:
    app: nginx-nodeservice
    demo: service-node
spec:
  containers:
  - name: nginx-nodepod
    image: nginx
    ports:
      - containerPort: 80
        name: http-web-svc-nodeport

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-node-service
spec:
  type: NodePort
  selector:
    app: nginx-nodeservice
    demo: service-node
  ports:
  - name: name-of-node-service-port
    protocol: TCP
    port: 80     # service port 
    targetPort: http-web-svc-nodeport  # container port
    nodePort: 30007 # node port
