---
apiVersion: v1
kind: Pod
metadata:
  name: config-pod 
spec: 
  containers:
    - name: config-pod
      image: nginx 
      ports: 
        - containerPort: 80
      env: 
        - name: course 
          valueFrom:
            configMapKeyRef:
              name: devops-config           # The ConfigMap this value comes from.
              key: course
        - name: trainer 
          valueFrom:
            configMapKeyRef:
              name: devops-config           # The ConfigMap this value comes from.
              key: trainer


---
apiVersion: v1
kind: Pod
metadata:
  name: config-pod-A1
spec: 
  containers:
    - name: config-pod-A1
      image: nginx 
      ports: 
        - containerPort: 80
      envFrom:
        - configMapRef:
            name: devops-config